all:
	cp figures/n_obs/edited_n_obs.eps figures.include/;
	cp figures/chi_dist/chi_dist_example.eps figures.include/;
	cp ~/Work/m33_miras/simulate_constant/figures/eii3022_it5_22408_i.eps figures.include/;
