all:
	cp figures/n_obs/edited_n_obs.eps figures.include/;
	cp figures/chi_dist/chi_dist_example_combined.eps figures.include/chi_dist_example.eps;
	cp figures/const_flc/epss/m00_8743.eps figures.include/const_flc_example.eps;
